INSERT INTO DIGITAL_URL (SHORT_URL,LONG_URL,EXPIRY_DATE,DESCRIPTION,CATEGORY, TRIBE, APPLICATION, USER_MAIL, BOOKMARK_TITLE)
VALUES ('kpys01','https://www.google.com','2020-10-20',null,null,null,null,null,null);

INSERT INTO DIGITAL_USER (EMAIL,PASSWORD,CATEGORY) VALUES ('sample@gmail.com', 'sample', 'tribe');
